### PR TITLE
Add Sentry to payment service

### PR DESCRIPTION
**Pull request by AbhiPrasad**
Add `@sentry/opentelemetry-node` to `paymentservice`.

@tonyo does that yaml config look right?

### CODE REVIEW

**Review by tonyo — APPROVED** [review]
Yes 👍

**Comment by tonyo** [comment]
Oh wait a sec, this line should be removed: https://github.com/getsentry/opentelemetry-demo/pull/3/files#diff-2655f4fdea68a3eaddeffb7cf0a80a498d2b3e111e3c76e3e03b79d4d764d906R11

**Review by tonyo — CHANGES_REQUESTED** [review]
Oh wait a sec, this line should be removed: https://github.com/getsentry/opentelemetry-demo/pull/3/files#diff-2655f4fdea68a3eaddeffb7cf0a80a498d2b3e111e3c76e3e03b79d4d764d906R11
(line 11 in sentry-components.yaml, to make it a valid YAML)

**Comment by AbhiPrasad** [comment]
Fixed with [e5e64f2](https://github.com/getsentry/opentelemetry-demo/pull/3/commits/e5e64f2039f8db8929033d72c69a28ef525fb6d6)

**Review by tonyo — APPROVED** [review]

**Pull request merged**
